# True if debug messages hit the logs.
debug: false

# If true, players with the fixleaves.notify permission will receive broadcasts
# about FixLeaves progress every 10s.
notify: true

# Period in ticks between chunk conversions.
period: 1

# Current index (position) of the next chunk to fix.
# Chunk (0,0) is index 0. Surrounding immediate neighbours are 1
# through 8, numbered left to right, then top top bottom. The SE
# diagonal (0,0), (1,1), (2,2) etc is index (N^2 - 1).
# e.g. SIDE = 5:
#
#   9  10  11  12  13
#  14   1   2   3  15
#  16   4   0   5  17
#  18   6   7   8  19
#  20  21  22  23  24
index: 0

# Length of the side of the square to fix, in chunks.
side: 1

# Lowest Y level to process.
min_y: 50

# Name of world to fix.
world: world